# Generated by Django 4.1.5 on 2023-01-25 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zmall", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategory",
                to="zmall.category",
            ),
        ),
    ]
