# Generated by Django 4.1.5 on 2023-01-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zmall", "0002_alter_product_location_alter_subcategory_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="zmall.product",
            ),
        ),
    ]
