# Generated by Django 4.1.5 on 2023-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationcode",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
